final String itemURL = "/item";
final String authorURL = '/author';
final String categoryURL = '/category';
final String filesURL = '/files';
final String seriesURL = '/seires';
final String itemImageURL = '/itemimage';
final String settingsURL = '/settings';
final wsPath = "websocket";
final serverPath = "server";
